### ISSUE TITLE
ModuleNotFoundError: No module named 'evdev'

### ISSUE THREAD

**Issue by HagRetek** [joaorb64/joycond-cemuhook#1]
Trying to use my Switch Pro Controller (wired via USB) on Ubuntu 18.04 LTS, running on Linux 5.3.0-45-generic. I already have both *dkms-hid-nintendo* and *joycond* installed and working, tested on Dolphin and PCSX2.
I also managed to clone this repo with no problems, but when I try running `joycond-cemuhook.py`, it returns an error message:
```bash
hag@hag-ubuntu:~/joycond-cemuhook$ python3 joycond-cemuhook.py
Traceback (most recent call last):
  File "joycond-cemuhook.py", line 2, in <module>
    import evdev
ModuleNotFoundError: No module named 'evdev'
```
The first thing I did was to install evdev, but it's already installed:
```bash
hag@hag-ubuntu:~/joycond-cemuhook$ pip install evdev
Collecting evdev
Installing collected packages: evdev
Successfully installed evdev-1.3.0
```
Running `joycond-cemuhook.py` again has the exact same result as before. I tried deleting the repo and cloning it again, but the issue still persisted. During all this, the controller was connected.
Nope, rebooting didn't work.

**Comment by HagRetek** [comment]
Didn't know they can also be installed as individual packages. Thanks a lot!
It seems to be working (bigger shakes show up as bigger motions etc), but I can't wrap my head around which axis is which. I hate asking, but could you give me any ideas how to set it up? (if controlling the IR sensor using the gyroscope in Dolphin is even possible)

**Comment by joaorb64** [comment]
On dolphin:

- Edit an emulated wiimote
- Reset configs to default
- On the top-left, select the DSU device
- Enable motion input from the DSU server on "Alternate Input Sources"

Motion inputs should be mapped automatically with even functioning pointer.
I don't remember if you can change the input device and still get motion inputs. If not, when configuring the buttons use right-click, select the device, test and select the buttons.

**Comment by joaorb64** [comment]
Also thanks for asking. Feedback is always welcome and helps me improve the instructions for the next users. Glad I can help!
