### ISSUE TITLE
Combined Joy-Cons' motion provider is assigned to camera

### ISSUE THREAD

**Issue by potatoeggy** [joaorb64/joycond-cemuhook#11]
After combining Joy-Cons, their motion input can no longer be detected in Dolphin or Cemu. Everything is normal if both are connected as separate controllers.

```
Looking for Nintendo Switch controllers...
Found Nintendo Switch Combined Joy-Cons - 
Slots: ['L+R', '0', '0', '0']
```

**Comment by joaorb64** [comment]
From your output, it seems like the combined joycons don't have a MAC address (should be printed after "Found Nintendo Switch Combined Joy-Cons - "). Usually, joycond gives the left joycon's MAC address to it. Well, let's try to investigate.
Are you using Nintendo-branded joycons? Are you using the latest version of hid_nintendo, joycond and joycond-cemuhook? What's your distro?

**Comment by potatoeggy** [comment]
> From your output, it seems like the combined joycons don't have a MAC address (should be printed after "Found Nintendo Switch Combined Joy-Cons - "). Usually, joycond gives the left joycon's MAC address to it. Well, let's try to investigate.

> Are you using Nintendo-branded joycons?
Yup

>Are you using the latest version of hid_nintendo, joycond and joycond-cemuhook? What's your distro?

I'm using Arch Linux on kernel 5.7.9.
```
$ pacman -Q hid-nintendo-dkms joycond-git joycond-cemuhook-git
hid-nintendo-dkms 2.0-2
joycond-git r76.08ffcc6-1
joycond-cemuhook-git r26.e51f79c-1
```

hid-nintendo-dkms was last updated on 12 June, joycond-git 8 June, and joycond-cemuhook-git 27 May.

Here is the output from `# joycond`:
```
adding epoll_subscriber: fd=4
Creating new phys_ctlr for /dev/input/event16
Found Right Joy-Con
driver_name: Nintendo Switch Right Joy-Con
MAC: 98:41:5C:60:A2:DA
adding epoll_subscriber: fd=5
Creating new phys_ctlr for /dev/input/event14
Found Left Joy-Con
driver_name: Nintendo Switch Left Joy-Con
MAC: 98:41:5C:61:3E:F5
adding epoll_subscriber: fd=15
Waiting controller needs partner
Found left
Waiting controller needs partner
Found right
adding epoll_subscriber: fd=25
Creating combined joy-con input
```

**Comment by joaorb64** [comment]
Just did a quick test, this is my output when running joycond-cemuhook:

```
$ python3 joycond-cemuhook.py 
Looking for Nintendo Switch controllers...
Select motion provider for Nintendo Switch Combined Joy-Cons: 
0 Nintendo Switch Combined Joy-Cons 
1 Nintendo Switch Right Joy-Con IMU B8:8A:EC:00:42:41
2 Nintendo Switch Left Joy-Con IMU B8:8A:EC:00:45:FD
1 # (I select the device)
Found Nintendo Switch Combined Joy-Cons - 
Slots: ['L+R', '0', '0', '0']
[udp] Client connected: 127.0.0.1:42593 # (Some emulator connected)
...
```
I also have similar output for joycond.
I'm using Ubuntu 20.04 on kernel 5.4.0-40.

Maybe it's a bug related to later kernel versions?

**Comment by potatoeggy** [comment]
I spammed a few print statements in the code, and it seems like `motion_d` is being set to my webcam? In this part specifically:

```python
                            for dd in evdev_devices:
                                if dd.uniq == d.uniq and dd != d:
                                    motion_d = dd
                                    print("dd is " + dd.uniq, dd.name) # temp debug
                                    break
```
```
dd is  Integrated Camera: Integrated C
```

`d.uniq` is blank, and my integrated camera's `dd.uniq` is also blank, so we never reach the part where I can select a motion provider. So I think the problem here is that `Nintendo Switch Combined Joy-Cons` does not have a MAC address assigned to it, weirdly.

```python
                            print(d.name, "|", d.uniq)
                            for dd in evdev_devices:
                                print(dd.name, "|", dd.uniq)
```

```
Nintendo Switch Combined Joy-Cons | 
Nintendo Switch Combined Joy-Cons | 
Nintendo Switch Right Joy-Con IMU | 98:41:5C:60:A2:DA
Nintendo Switch Left Joy-Con IMU | 98:41:5C:61:3E:F5
Integrated Camera: Integrated C | 
MSFT0004:00 06CB:CD98 Touchpad | 
MSFT0004:00 06CB:CD98 Mouse | 
HD-Audio Generic Headphone | 
HD-Audio Generic Mic | 
HDA Digital PCBeep | 
PC Speaker | 
HD-Audio Generic HDMI/DP,pcm=7 | 
HD-Audio Generic HDMI/DP,pcm=3 | 
Ideapad extra buttons | 
AT Translated Set 2 keyboard | 
Video Bus | 
Power Button | 
Lid Switch | 
```

I'll fiddle around some more and try to find out why that is soon.

**Comment by potatoeggy** [comment]
Actually, it seems like from your output that the combined Joy-Con device is supposed to have a blank `dd.uniq`.

I worked around the problem by forcing manual selection of `motion_d`:
```
                            """ # just comment everything out
                            for dd in evdev_devices:
                                if dd.uniq == d.uniq and dd != d:
                                    motion_d = dd
                                    break
                            """
```

For whatever reason, I have a lot more input devices in evdev. What's this loop for?

**Comment by joaorb64** [comment]
This loop looks for the device with same Mac address (uniq) as the device found. For example, if you connect a Left Joycon it will find the corresponding Left Joycon IMU to assign as motion provider.
Because combined joycons don't expose a uniq, I made the alternative route to manually select a device from the list. I guess I'll have to change this part so it doesn't assign to some random device like it did in your case :P
Thank you so much for the help, by the way!
