### ISSUE TITLE
Upcoming change to right joy-con's axes

### ISSUE THREAD

**Issue by DanielOgorchock** [joaorb64/joycond-cemuhook#13]
My new revision to the IMU patch: https://github.com/DanielOgorchock/linux/commit/4a14fc82298a36e70c5e9dc809cdff8c4f68517e negates the right joy-con's Z and Y axes to make them consistent with the pro controller and left joy-con. This change is only in my repo for now, but when it makes its way to the dkms module, it will likely impact joycond-cemuhook I'd assume.

The patch also improves the precision of the gyro data reported to userspace, which is a nice bonus. Not sure how impactful that will end up being.

**Comment by joaorb64** [comment]
I'll take a look as soon as possible. Excited with the improved precision!

**Comment by joaorb64** [comment]
I ended up not saying it, but the update is available on https://github.com/joaorb64/joycond-cemuhook/tree/develop branch while your change doesn't hit https://github.com/nicman23/dkms-hid-nintendo.
