### ISSUE TITLE
no absinfo() attr found 

### ISSUE THREAD

**Issue by linuxsphere** [joaorb64/joycond-cemuhook#16]
I got following error: 

Using [Nintendo Switch Right Joy-Con IMU] as motion provider for [Nintendo Switch Right Joy-Con]
Slots: ['R', '0', '0', '0']
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "joycond-cemuhook.py", line 129, in handle_motion_events
    axis = self.motion_device.absinfo(event.code)
AttributeError: 'InputDevice' object has no attribute 'absinfo'

I am using evdev 1.2.0

**Comment by joaorb64** [comment]
Seems like this function was created on python-evdev 1.3.0. Could you try installing it via pip?
On Ubuntu I'm using `sudo pip3 install python-evdev`.
I should really create a dependencies file for setting this up more easily 😅

**Comment by joaorb64** [comment]
With the recently added `requirements.txt`, the newest version of evdev will be installed and this won't be an issue. Closing this issue.
