### ISSUE TITLE
Lose input for like 10 seconds frequently

### ISSUE THREAD

**Issue by paperstiger** [joaorb64/joycond-cemuhook#17]
This package is a great tool for using dolphin on linux and I got it working for skyward sword, well, in most of the time. One issue that's bothering me is in about every 30 seconds (a rough estimate) the emulator is not receiving any input from my controller (for both button pressing and gyro input) for about 15 seconds. This problem just repeats. What could be going on here? I'm building dolphin from source if it helps to debug.

**Comment by joaorb64** [comment]
Does this happen only when using joycond-cemuhook (mapping everything to the DSU device on Dolphin) or does it also happen with default joycond/hid_nintendo?

**Comment by paperstiger** [comment]
Could you please explain how I could debug it? Like how to run evtest on the controller? I am not quite familiar with how the system is working now.

**Comment by joaorb64** [comment]
I'm sorry for not explaining it before. My first suspicion would be that it's a problem more related to the lower-level systems, like the driver or even your bluetooth adapter. If you open a terminal and run `evtest`, it should list your controller along with other devices, and ask which one you'd like to test. It'll log every input coming from the controller. As the analog sticks are very sensitive, it'll kind of spam its readings on the console window.

If at any point this logging stops, the problem should be coming from those lower level systems: joycond? hid_nintendo? bluetooth adapter/driver?

If it doesn't, it's a problem in joycond-cemuhook itself.

**Comment by paperstiger** [comment]
It keeps printing stuff and now my issue is it's in games it seems that the left analog is kept pressed so Link keeps walking forward. All my other inputs do not work or are laggy.

**Comment by paperstiger** [comment]
More on this, I print the integer data in your code and it freezes frequently so I suspect it's your issue.

**Comment by paperstiger** [comment]
OK. By lots of debugging I figured it out. It turns out sometimes reading battery status takes too long. So I just comment that function and hard code the battery value.

**Comment by joaorb64** [comment]
Oh, wow. I didn't know reading the battery status had that kind of impact in the code. And to be honest, most emulators don't even use this information... I could consider removing it completely or try a better implementation. Thanks for the debugging work, I'll take a look at it as soon as I can!

**Comment by joaorb64** [comment]
Fixed with https://github.com/joaorb64/joycond-cemuhook/commit/e9dda77e168b74f2fc4dd30467dfa6cd48e0e7ad. Could you test it for me?
