### ISSUE TITLE
UDPServer talks to no one

### ISSUE THREAD

**Issue by meisiek** [joaorb64/joycond-cemuhook#19]
No emulator on my windows PC gets any data from the UDPServer on my Raspberry 4. When joycond-cemuhook is started the following text appears:

```
python3 joycond-cemuhook.py -v
Looking for Nintendo Switch controllers...
Found [Nintendo Switch Pro Controller] - mac: 7C:BB:8A:FB:37:5B
Using [Nintendo Switch Pro Controller IMU] as motion provider for [Nintendo Switch Pro Controller]
Debug: Input events thread started
Debug: Motion events thread started
Debug: Found dbus interface for battery level reading. Value: 100.0
Debug: Battery level reading thread started
======================== Slots ========================
Device         Battery Lv   Motion Dev   MAC Addr    
1 🎮 Pro        100.0 ▊      ✔️           7C:BB:8A:FB:37:5B
2 ❎ 
3 ❎ 
4 ❎ 
=======================================================
```

But thats it. No emulator gets any data from it. I tried it in Citra, configured motion source to Cemuhook UDP with IP and port from my raspberry, but every click on the "Test" button gives "no valid data received".
PadTest_1011 won't connect either.

One missing dependency I did find was "upower". Are there other dependencies missing?

A port test from my windows machine to the raspberry:
TCP port 26760 (unknown service): NOT LISTENING
UDP port 26760 (unknown service): LISTENING or FILTERED

I guess that rules out firewall problems. And there is no firewall installed on my raspberry and I opened all UDP ports to Citra on my pc.

**Comment by meisiek** [comment]
I installed BetterJoy on a second windows computer and it also can't connect to Citra on my main PC.
This issue can be closed. Sorry

**Comment by meisiek** [comment]
Ok, figured it out. Just in case someone else has the same problem:
You have to edit the joycond-cemuhook.py file and change the IP from 127.0.0.1 to the IP of your linux box.
127.0.0.1 only works if joycond-cemuhook runs on the same computer as the emulator.

It would be nice if you could pass the IP to the python file by a command line parameter or edit it in a separate config file.

**Comment by joaorb64** [comment]
Oh, wow. So you're using one device only as display and input handling while using other device for processing? Nice thing you ended up getting it to work.
I'll definitely add an option to change IP and Port. Thanks for your input :)

**Comment by meisiek** [comment]
The emulator runs on my main PC, but I want to play in a different room on my TV. So I bought a raspberry 4, installed a steam client on it and on you go.
And your program ist perfect for the job, because my TV is too far away from my PC so the gamepad is paired to the raspberry and sends everything to my PC.
And all this works really well, the input lag is so low that it doesn't bother me at all.

**Comment by joaorb64** [comment]
Solved with https://github.com/joaorb64/joycond-cemuhook/commit/8050277ad0623f1773e606a403584b03aa15a38d.
