### ISSUE TITLE
Instead of wine workaround use actual fix

### ISSUE THREAD

**Issue by v1993** [joaorb64/joycond-cemuhook#2]
There's this line that's causing problems that lead to wine workaround being required:

https://github.com/joaorb64/joycond-cemuhook/blob/master/joycond-cemuhook.py#L186

`chrippa/ds4drv` have a fix for this problem in this commit (it fixes timestamp encoding and removes workaround):

https://github.com/TheDrHax/ds4drv-cemuhook/commit/c90144a14830964d425ab25ef08acba84f7269d7

This will make wine workaround not needed anymore with behavior always correct so it can be removed at all. I don't have time now to purge everything wine-workaround related, but is should be trivial for anyone familiar with this code.

**Comment by joaorb64** [comment]
Hey, thanks for this. I've already worked this out but ended up mixing another functionality with it and didn't fully finish it for a release. It's on a secondary branch. I'm releasing this fix soon! ™️

**Comment by joaorb64** [comment]
Just merged a PR that fixes it!

**Comment by v1993** [comment]
I guess I'll close it then. Thanks!
