### ISSUE TITLE
Noncompliance with cemuhook update requests causes multiple reconnections

### ISSUE THREAD

**Issue by terencode** [joaorb64/joycond-cemuhook#4]
See https://github.com/TheDrHax/ds4drv-cemuhook/pull/7.

**Comment by joaorb64** [comment]
Well, copied the solution from https://github.com/TheDrHax/ds4drv-cemuhook/commit/8d3e12650eb2d91c9ec4cc5c0ffd61fc33bb4ad3 and pushed https://github.com/joaorb64/joycond-cemuhook/commit/268c12fe73bff4822fd509f086e5ec77c1fa90ee

**Comment by terencode** [comment]
Tested and working, thank you!
