### ISSUE TITLE
Server doesn't seem to be running

### ISSUE THREAD

**Issue by dodgypast** [joaorb64/joycond-cemuhook#40]
I'm running arch, kernel version: 5.10.16.arch1-1

I have installed and enabled joycond-git .

When I try to run I get the following:
`[duncanm@arch joycond-cemuhook]$ python3 joycond-cemuhook.py
Looking for Nintendo Switch controllers...
More than four players detected. Ignoring player 1.
`

When I try to detect the sever from yuzu I get:
![image](https://user-images.githubusercontent.com/24266439/108374789-ea049700-7233-11eb-90da-ac11fab6432a.png)

I've tried the same controller in windows with betterjoy acting as a server and it works fine.

Any ideas what might be the problem?

**Comment by joaorb64** [comment]
I won't be able to test this in the next few days, @gal20 was very active recently, if you can check this out?

Once in the Yuzu Discord server I heard this test button doesn't work, but the input itself does (I had problems with this too but I could configure motion input normally, the way I described on the wiki page).

But from your output, if that's all the program gave you, seems like a bug on the initial controller detection. Can you test if https://github.com/joaorb64/joycond-cemuhook/tree/cc370fb8bc0ce6612230d747bc97916882fccaf3 works for you?

**Comment by dodgypast** [comment]
Unfortunately it has the same output and problem:
`[duncanm@arch joycond-cemuhook-cc370fb8bc0ce6612230d747bc97916882fccaf3]$ python3 joycond-cemuhook.py
Looking for Nintendo Switch controllers...
More than four players detected. Ignoring player 1.
`
But I get some extra output:
`[udp] Client connected: 127.0.0.1:60268
[udp] Client connected: 127.0.0.1:50179
[udp] Client connected: 127.0.0.1:43810
[udp] Client connected: 127.0.0.1:55726
`

Also I've tested it with dolphin and nothing is being detected, unlike in windows and betterjoy.

One thought, could there be a problem because I'm using kernel 5.10, which has the switch switch pro controller driver rolled in, but I'm still having to install hid-nintendo-dkms?

**Comment by joaorb64** [comment]
Wait... did you press R+L to assign the controller?

Without hid_nintendo (either kernel or dkms module): lights blink all the time, analog ranges are screwed
With hid_nintendo: controllers connect and are assigned as p1 immediately
With joycond: controllers blink lights until you press R+L, for you to select their order and most importantly to assign Joycons as Combined R+L or single, sideways

**Comment by gal20** [comment]
The Linux kernel still does not have the hid-nintendo driver (The file `hid-nintendo.c` should exist in `drivers/hid/`, but I couldn't find the find when I checked the latest source code (5.11) in [kernel.org](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hid?h=v5.11)). So you should install the dkms module for now.

As for the issue, I'll open a PR to add stricter filtering of the evdev devices to try to avoid such problems.

**Comment by dodgypast** [comment]
Thanks for both your help, not exactly sure why, but it started working perfectly.
![image](https://user-images.githubusercontent.com/24266439/108482451-13710180-72cc-11eb-8a80-829145679ab7.png)

**Comment by joaorb64** [comment]
What in the world is that LED Status, haha. I wonder what made it suddenly work though...
