### ISSUE TITLE
Faliure to load a "modinfo" file or directory on initial startup

### ISSUE THREAD

**Issue by ZaptorZap** [joaorb64/joycond-cemuhook#46]
Running Debian 10 (buster) x86_64
Python 3.7.3 with GCC 8.3.0
Hey so first I'd like to express my apologies for being a bit inexperienced when it comes to this platform, and **especially** the language this code is based on. All I have is the errno message alongside a traceback, shared below: 
```
Traceback (most recent call last):
  File "joycond-cemuhook.py", line 779, in <module>
    main()
  File "joycond-cemuhook.py", line 750, in main
    process = subprocess.Popen(["modinfo", "hid_nintendo"], stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modinfo': 'modinfo'
```
This errno occurs directly after running the `python3 joycond-cemuhook.py` command as instructed in the final step of [the README's "How to use" section](https://github.com/joaorb64/joycond-cemuhook/blob/master/README.rst#how-to-use)

I did some googling around and ended up with the vague conclusion that `PATH` is somehow being set to the current directory, instead of some system library directory. In a quick fit of desperation, I tried to search, from the root directory, *any* mention of "modinfo" and I came up empty handed with some golang example files.

Might be worth mentioning I'm running this in a mounted storage device located in `/mnt/storage/` instead of the home directory? I can't imagine how that'd matter but there ya go.

**Comment by joaorb64** [comment]
Can you try running `modinfo -h` in a terminal?
The idea of this part of the code is to check if `hid-nintendo` is installed at all. If it's installed but it still won't run maybe you could try removing this part of the code. If you need further help in exactly which lines to remove please let me know so I can check it.

**Comment by ZaptorZap** [comment]
All I get is a simple:
> ```
> bash: modinfo: command not found
> ```
`apt` doesn't appear to have a "modinfo" package either.

**Comment by joaorb64** [comment]
From a quick search, seems like the package name is `kmod`. Can you try it out?

**Comment by ZaptorZap** [comment]
```
kmod is already the newest version (26-1).
```
the `kmod` command by itself does specify that "kmod handles gracefully if called with the modinfo symlink" (not exact language but you get the point)

**Comment by ZaptorZap** [comment]
Oh hold on! `sudo modinfo -h` gets me some responses. Throwing sudo privileges at `python3 joycond-cemuhook.py` now throws a *different* error:
```
Traceback (most recent call last):
  File "joycond-cemuhook.py", line 3, in <module>
    import pyudev
ModuleNotFoundError: No module named 'pyudev'
```

**Comment by ZaptorZap** [comment]
Annnnd after running `sudo pip3 install -r requirements.txt`, `sudo python3 joycond-cemuhook.py` runs the cemuhook integration as intended.
