### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by phisch** [joaorb64/joycond-cemuhook#47]
Do you mind adding a license to the project? (MIT for example)

**Comment by uumas** [comment]
(OT but didn't find a way to contact you) Is this related to [this](https://www.youtube.com/watch?v=deC1_h3Z2d8) video? You seem to have a fix for #48 but aren't comfortable uploading it due to licensing problems?

**Comment by phisch** [comment]
@uumas my fix isn't done, i do have a working implementation for gyro drift compensation (through a calibration process). Basically the controller records drift whenever it is placed on a surface and not moved for 1 second, and then it subtracts that drift from future readings. This is already a lot better, but the raw gyro data is still very jittery (as it usually is). I want to implement Kalman sensor fusion to get cleaner orientation data that can be used for a lot smoother input, but i kinda suck at math and need some more time to get it done.

But yes, this also is kinda related to it. I don't contribute to projects that don't have a proper license. If this project doesn't add a license, i will just contribute the algorithm to another one that does, like https://github.com/v1993/evdevhook for example. Even though i'd prefer MIT over GPL, because GPL is basically a virus disguised as a license. (still better than none :P)

**Comment by joaorb64** [comment]
I'll add a license ASAP, just need a quick read about licensing because I've never done this before. Sorry for the late response!

**Comment by joaorb64** [comment]
Funny how my Pro seems to be very precise, but my Right Joycon tends to drift towards left and a bit down. In the past I experimented with a simple deadzone and other simpler filtering approaches because it was really bad but some changes in the base driver made it so much better that I reverted it. Should be an awesome feature!

**Comment by phisch** [comment]
Thanks for adding the MIT license. Good choice!
I'll try to get my sensor fusion stuff ready over the weekend and hopefully send a PR your way.

Closing this as a license was added.
