### ISSUE TITLE
not mapping HOME and CAPTURE buttons of Switch Pro Controller

### ISSUE THREAD

**Issue by cipitaua** [joaorb64/joycond-cemuhook#49]
Everything works fine with the switch pro controller, buttons and motion works great, except that `home` and `capture` buttons are not recognized by the DSU client (cemu), and thus they are unusable.

These buttons works fine at driver level (see 'PRESSED'):

![image](https://user-images.githubusercontent.com/4388859/118408413-d2e41280-b685-11eb-9810-353af07f7b62.png)

but proper mapping is missing in `joycond-cemuhook`

**Comment by joaorb64** [comment]
From https://github.com/joaorb64/joycond-cemuhook/blob/master/profiles/Nintendo%20Switch%20Pro%20Controller.json, `Home` should be assigned to `PS` and capture really isn't assigned to any button. It's supposed to be:
```
Home → PS (home)
Start → Options
Select → Share
```

**Comment by cipitaua** [comment]
Thank you for the reply. It's not clear how to change the json, for example if I put
```
    "button_share": "BTN_SELECT",
    "button_options": "BTN_START",
    "button_ps": "BTN_HOME",
```
I get  a `KeyError: 'BTN_HOME'`

**Comment by cipitaua** [comment]
By looking at `hid-nintendo.c` I could understand that `BTN_MODE` and `BTN_Z` correspond to `home` and `capture`, respectively. However, both `"button_ps": "BTN_MODE"` and `"button_ps": "BTN_Z"` are recognized by cemu, which evidently does not grab the `PS` button. That's strange, since cemuhook was conceived indeed for cemu :(

**Comment by cipitaua** [comment]
Here https://v1993.github.io/cemuhook-protocol/ it says that PS button is unused.

**Comment by joaorb64** [comment]
Oh. So the buttons are mapped and sent (visible via Dolphin), but Cemu itself doesn't use those buttons at all? Maybe if you use custom mappings?
You can also use joycond-cemuhook only for motion and manually map the buttons using the original evdev/js device in Cemu, if it has a mapping for those.

**Comment by cipitaua** [comment]
> You can also use joycond-cemuhook only for motion and manually map the buttons using the original evdev/js device in Cemu, if it supports mapping those in the UI.

I don't think it's possible: cemu gets everything from the same source, that can be evdev/js or cemuhook server. It can't be  (or at least I could not) configured to take buttons from evdev/js and motion from cemuhook.  In [Yuzu](https://github.com/yuzu-emu/) it is possible and indeed it works fine.
