### ISSUE TITLE
Error when pairing

### ISSUE THREAD

**Issue by PranavSakthivel** [joaorb64/joycond-cemuhook#51]
Hi, I'm running Fedora 34 KDE. I got the pairing to work, I saw all the LEDs flashing after pairing via bluetooth, and pressing both triggers changed the LED to player 1. As soon as this happens, the program keeps repeating this info:

Cemu does not detect the controller at all. 

```
Device disconnected: Nintendo Switch Pro Controller
Task exception was never retrieved
future: <Task finished name='Task-181' coro=<SwitchDevice._handle_motion_events() done, defined at /home/pranav/Programs/joycond-cemuhook/joycond-cemuhook.py:199> exception=AttributeError("'InputDevice' object has no attribute 'absinfo'")>
Traceback (most recent call last):
  File "/home/pranav/Programs/joycond-cemuhook/joycond-cemuhook.py", line 210, in _handle_motion_events
    axis = self.motion_device.absinfo(event.code)
AttributeError: 'InputDevice' object has no attribute 'absinfo'
================= ('127.0.0.1', 26760) ================
Device         LED status   Battery Lv   MAC Addr    
1 ❎ 
2 ❎ 
3 ❎ 
4 ❎ 
=======================================================

================= ('127.0.0.1', 26760) ================
Device         LED status   Battery Lv   MAC Addr    
1 🎮 Pro       ■ □ □ □      55.0 ▄       60:6B:FF:19:2F:DA
2 ❎ 
3 ❎ 
4 ❎ 
=======================================================
```

**Comment by gal20** [comment]
`AttributeError: 'InputDevice' object has no attribute 'absinfo'` suggests your `evdev` module is too old. Try to update it to the latest version.

**Comment by joaorb64** [comment]
@gal20 do you know what's the minimum version for it to work properly? I think someone else had this same issue before, maybe we could ensure the version in the dependencies txt and in the program itself.

**Comment by PranavSakthivel** [comment]
> `AttributeError: 'InputDevice' object has no attribute 'absinfo'` suggests your `evdev` module is too old. Try to update it to the latest version.

Hi, thanks for the response. I grabbed the latest version of evdev I could I could using the fedora repository/dnf. How would I get this updated?

**Comment by gal20** [comment]
@PranavSakthivel The fedora dnf for the evdev module is `python3-evdev`. You can either remove it and then run `pip install evdev`, or you can keep it and run `pip install --upgrade evdev`.

@joaorb64 The [changelog](https://python-evdev.readthedocs.io/en/latest/changelog.html) says `absinfo` was added in 1.3.0.

**Comment by PranavSakthivel** [comment]
Thanks so much, that seems to get everything except rumble working on Cemu. For future reference, I had to install python3-devel to get pip install evdev to work.

**Comment by joaorb64** [comment]
@PranavSakthivel the cemuhook protocol doesn't process rumble. For that, you can use a mixed configuration: configure the controller from the config menus using the evdev device (which has rumble) and then pull only motion from cemuhook.
