### ISSUE TITLE
No longer working with UPower 0.99.18

### ISSUE THREAD

**Issue by CommandMC** [joaorb64/joycond-cemuhook#63]
Hello,
I'm running this on EndeavourOS (basically Arch Linux) & updated to kernel 5.17.8 yesterday. Today, when booting this up, I'm met with [this stacktrace](https://gist.github.com/CommandMC/fac65316c36e3553f2a0d96f6b561169#file-stacktrace-py) after connecting my controller (Switch Pro).

[Full list of upgraded packages](https://gist.github.com/CommandMC/fac65316c36e3553f2a0d96f6b561169#file-upgraded_packages) (most of them are probably irrelevant, but just in case)

I'm using the [AUR package](https://aur.archlinux.org/packages/joycond-cemuhook-git), but I was also able to reproduce the issue by following the "How to use" instructions in this repo

Let me know if you need anything else to help debug this

**Comment by CommandMC** [comment]
Update: This seems to be caused by a bug in the `upower` package on Arch. I've now downgraded from `0.99.18-1` to `0.99.17-1` for now, will report this to them in the coming days

**Comment by CommandMC** [comment]
I've now opened up https://gitlab.freedesktop.org/upower/upower/-/issues/190 to track the issue on UPower's side. Will re-open the issue if this is a deliberate change (which it seems not to be, considering their documentation still mentions this method)

**Comment by joaorb64** [comment]
Hi! Sorry for not getting back to you in time. If this Refresh method was deprecated, we can definitely add a check and use the new function name if the user has this package in a newer version!

**Comment by CommandMC** [comment]
[This commit](https://gitlab.freedesktop.org/upower/upower/-/commit/d0ebbe32bb5cec06335a7bd0f11f8550deaec16e) is probably what broke it

**Comment by CommandMC** [comment]
So uh, just to test, I've removed the two lines where `Refresh` is called and everything seems to still work?

**Comment by CommandMC** [comment]
Fixed with a82dbf7e23f9b9c5142034e75af9aae09d113822
