### ISSUE TITLE
Unable to map buttons on CEMU 1.18.2c

### ISSUE THREAD

**Issue by CCF100** [joaorb64/joycond-cemuhook#7]
If I try to use the built in DSU client on CEMU, I can map joysticks, but not buttons... If I try to just map the controller buttons with DirectInput like normal and use Cemuhook, Cemuhook doesn't properly intrepret the gyro... However, If I try to use Dolphin, it works just fine...

**Comment by joaorb64** [comment]
Could reproduce. I'll look into it.

**Comment by joaorb64** [comment]
I just pushed https://github.com/joaorb64/joycond-cemuhook/commit/e51f79cd425660bd590739d483d2c4fadd6093ae, and from my tests it fixes your issue. Can you test it?
