### ISSUE TITLE
Stuck on "Looking for Nintendo Switch controllers..."

### ISSUE THREAD

**Issue by PowerUser64** [joaorb64/joycond-cemuhook#9]
I have all dependencies installed, and my controller is connected via bluetooth (tried wired too), but when I start joycond-cemuhook, it doesn't get past "Looking for Nintendo Switch controllers...". I am trying to use a pro controller. One good thing is the server is up and seems to be responding.

**Comment by JaredBrian** [comment]
I had this same problem. I tried to use the joy-cons themselves in single and double mode and nothing.

**Comment by joaorb64** [comment]
When looking for controllers it searches evdev for devices with one of the following makes: "Nintendo Switch Left Joy-Con", "Nintendo Switch Right Joy-Con", "Nintendo Switch Pro Controller", "Nintendo Switch Combined Joy-Cons".

Can you confirm what's the name of your evdev devices? (You can run `sudo evtest` to list all devices)

**Comment by JaredBrian** [comment]
yes the joy cons do appear as they should when using evtes, here's the output:

> No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Power Button
/dev/input/event1:	Power Button
/dev/input/event2:	Lite-On Technology USB Productivity Option Keyboard( has the hub in # 1 )
/dev/input/event3:	Logitech M510
/dev/input/event4:	Microsoft X-Box 360 pad
/dev/input/event5:	HDA ATI SB Front Mic
/dev/input/event6:	Lite-On Technology USB Productivity Option Keyboard( has the hub in # 1 )
/dev/input/event7:	HDA ATI SB Rear Mic
/dev/input/event8:	HDA ATI SB Line
/dev/input/event9:	HDA ATI SB Line Out Front
/dev/input/event10:	HDA ATI SB Line Out Surround
/dev/input/event11:	HDA ATI SB Line Out CLFE
/dev/input/event12:	HDA ATI SB Line Out Side
/dev/input/event13:	HDA ATI SB Front Headphone
/dev/input/event14:	HDA NVidia HDMI/DP,pcm=3
/dev/input/event15:	HDA NVidia HDMI/DP,pcm=7
/dev/input/event16:	HDA NVidia HDMI/DP,pcm=8
/dev/input/event17:	HDA NVidia HDMI/DP,pcm=9
/dev/input/event20:	Nintendo Switch Left Joy-Con
/dev/input/event21:	Nintendo Switch Left Joy-Con IMU
/dev/input/event22:	Nintendo Switch Combined Joy-Cons
Select the device event number [0-22]: 22
Input driver version is 1.0.1
Input device ID: bus 0x6 vendor 0x57e product 0x2008 version 0x0
Input device name: "Nintendo Switch Combined Joy-Cons"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 256 (BTN_0)
    Event code 257 (BTN_1)
    Event code 258 (BTN_2)
    Event code 259 (BTN_3)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
    Event code 318 (BTN_THUMBR)
    Event code 544 (BTN_DPAD_UP)
    Event code 545 (BTN_DPAD_DOWN)
    Event code 546 (BTN_DPAD_LEFT)
    Event code 547 (BTN_DPAD_RIGHT)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    144
      Min   -32767
      Max    32767
      Fuzz     250
      Flat     500
    Event code 1 (ABS_Y)
      Value  -2823
      Min   -32767
      Max    32767
      Fuzz     250
      Flat     500
    Event code 3 (ABS_RX)
      Value   -620
      Min   -32767
      Max    32767
      Fuzz     250
      Flat     500
    Event code 4 (ABS_RY)
      Value   -134
      Min   -32767
      Max    32767
      Fuzz     250
      Flat     500
  Event type 21 (EV_FF)
    Event code 80 (FF_RUMBLE)
    Event code 81 (FF_PERIODIC)
    Event code 88 (FF_SQUARE)
    Event code 89 (FF_TRIANGLE)
    Event code 90 (FF_SINE)
    Event code 96 (FF_GAIN)
Properties:
Testing ... (interrupt to exit)
Event: time 1593636741.537477, type 3 (EV_ABS), code 0 (ABS_X), value 105
Event: time 1593636741.537477, -------------- SYN_REPORT ------------
Event: time 1593636742.617604, type 3 (EV_ABS), code 1 (ABS_Y), value -2857
Event: time 1593636742.617604, -------------- SYN_REPORT ------------
Event: time 1593636744.462494, type 3 (EV_ABS), code 0 (ABS_X), value 68
Event: time 1593636744.462494, -------------- SYN_REPORT ------------
Event: time 1593636818.567012, type 3 (EV_ABS), code 3 (ABS_RX), value -577
Event: time 1593636818.567012, -------------- SYN_REPORT ------------

**Comment by PowerUser64** [comment]
My pro controller doesn't show up with `evtest` in wired or wireless mode, but says it is connected on the controller. It also shows up on the PC in gnome settings while in bluetooth mode. :thinking:

**Comment by joaorb64** [comment]
Is your pro controller Nintendo-branded?
I'll try to test some stuff today and try to investigate your bug, but I'm not really sure on how to replicate it...

**Comment by JaredBrian** [comment]
I'm using Linux mint 20 with Linux kernel 5.4.0-40

**Comment by potatoeggy** [comment]
@JaredBrian Please try running this branch: https://github.com/potatoeggy/joycond-cemuhook/tree/debug and tell us what it outputs?

**Comment by PowerUser64** [comment]
I do not have access to my computer right now (I'm on vacation), but the controller I am using is an 8bitdo SN30 Pro in switch mode. I have tried connecting it to my computer in other modes, such as Xinput or direct input mode, and it does show up with `sudo evtest`. This makes me think it might be some sort of driver issue, but I have the hid-nintendo driver installed (from the AUR). When I get home next week, I will run @potatoeggy's suggestion, and see what happens.

**Comment by potatoeggy** [comment]
@PowerUser64 It appears that your controller isn't Nintendo-branded. As such, hid-nintendo and subsequently joycond and finally joycond-cemuhook might not be able to recognise it. There can be subtle differences in how third-party controllers operate which can cause compatibility issues.

My debug branch only debugs issues if evdev can see the device; if your controller doesn't show up in evtest it's not going to help much. Apparently BetterJoyForCemu can see it after some searching when paired using Bluetooth. Does your controller work in Linux in other apps (e.g., Steam)?

**Comment by PowerUser64** [comment]
I have only gotten it to work with other systems, like the Nintendo switch, my Windows install, and my android phone. Steam doesn't even recognize it in Linux. I can use the other input modes to get input into my Linux box, but it doesn't send gyro data in the other input modes. 
Like I said, it's probably some kind of driver thing, and I'll have to do some more research on my controller to see how Linux compatible it is, and if there's anything I can do about this.

**Comment by JaredBrian** [comment]
alright so after using the debug build after it seems the master build was updated as well, here what I get. with the normal build, it seems like it is connected to dolphin but it isn't registering any movement from the joy-cons other than the standard button press input.
here is the debug output log:

python3 joycond-cemuhook.py
Looking for Nintendo Switch controllers...
Select motion provider for Nintendo Switch Combined Joy-Cons: 
0 Nintendo Switch Combined Joy-Cons 
1 Nintendo Switch Right Joy-Con IMU D4:F0:57:DF:86:A9
2 Nintendo Switch Left Joy-Con IMU D4:F0:57:E1:33:40
3 Microsoft X-Box 360 pad 
1
Using Nintendo Switch Right Joy-Con IMU as motion provider for Nintendo Switch Combined Joy-Cons
Found Nintendo Switch Combined Joy-Cons - 
Slots: ['L+R', '0', '0', '0']
DEBUG: The following text should not be True: False
DEBUG: Ignoring Nintendo Switch Right Joy-Con IMU as it is not a Nintendo Switch controller
DEBUG: Ignoring Nintendo Switch Left Joy-Con IMU as it is not a Nintendo Switch controller
DEBUG: Ignoring Microsoft X-Box 360 pad as it is not a Nintendo Switch controller
DEBUG: Nintendo Switch Combined Joy-Cons already added, not going to add it again
DEBUG: Nintendo Switch Combined Joy-Cons already added, not going to add it again


from here it loops the line:
  DEBUG: Nintendo Switch Combined Joy-Cons already added, not going to add it again

over and over again until i stop the program. and once i open up dolphin i get a confirmation: 
  [udp] Client connected: 127.0.0.1:40080

and then again later i get a similar message but without me having done anything yet:
   [udp] Client connected: 127.0.0.1:42155

later again i got this message again:
   [udp] Client connected: 127.0.0.1:40080

all meanwhile it is spamming:
   DEBUG: Nintendo Switch Combined Joy-Cons already added, not going to add it again 

if instead, I choose to use the joy-cons as a pair or the left joy-con it does the same thing regardless if they are both connected via Bluetooth to my PC or no. also important to note that the IPs above are not the same port as the one that appears in dolphin which is 127.0.0.1:26760.

**Comment by potatoeggy** [comment]
So it seems like everything is working normally. Did you set your controls using the DSUClient device in Dolphin? 
![image](https://user-images.githubusercontent.com/25178974/87990468-0c71de80-cab2-11ea-863e-a23c4458a648.png)

**Comment by JaredBrian** [comment]
ok so one thing i didnt know is i thought that you were supposed to set the device to the gamepad setting instead of the: evdev/0/Nintendo Switch Combined Joy-Cons. so after switching that i was at least get the game to start (Im using skyward sword as a test) and be able to press buttons to navigate through the menu but i am not able to move the cursor with the motion controls, and as far as i can tell from the controller config menu under the motion input tab (or any of the other tabs) its not picking up any motion at all.

So here's my setup: 
![Screenshot from 2020-07-20 16-08-53](https://user-images.githubusercontent.com/9028287/87991380-50a9b280-caa3-11ea-9ae3-d04e2f25091c.png)

and i have it set up to be an emulated Wii mote and emulate the wii's Bluetooth adapter. is there anything else im missing?

**Comment by potatoeggy** [comment]
I don't think motion controls work with the nunchuk (maybe?). Also check if this page is filled out: 
![image](https://user-images.githubusercontent.com/25178974/87991884-f87bac00-cab4-11ea-8940-2d564cf40eb4.png)

If the blue and red dots aren't moving, click "Default" at the top for Dolphin to recalibrate the gyro.

**Comment by JaredBrian** [comment]
ohh ok yup that did it, when I clicked on the buttons individually I couldn't get anything to appear. so yah it defiantly was stuck on looking for the controllers before. so whatever you did in the last update fixed it for me and I just didn't know how to set it up in dolphin correctly. and i didn't have to uncheck the nun-chuck for it to work. thanks for the help.

**Comment by joaorb64** [comment]
(From the discussion here I see the need for a configuration guide, I'll work on one soon)

**Comment by potatoeggy** [comment]
> (From the discussion here I see the need for a configuration guide, I'll work on one soon)

It seems like the issues so far come from Cemuhook itself being difficult to configure with different emulators (still might be helpful to put up a guide still) and not enough output from joycond-cemuhook, so maybe implement a `--verbose`/`--debug` argument?

**Comment by JaredBrian** [comment]
yah i agree that would be very helpful.

**Comment by joaorb64** [comment]
As I recently added a verbose argument and the controller itself is third-party (refer to https://github.com/DanielOgorchock/linux/issues/10), I'm closing this issue.

**Comment by PowerUser64** [comment]
I just re-visited this project and now everything works! The issue was `hid-nintendo` not having full support for my controller at the time. Thanks for all the effort you've put into this!

**Comment by nezartarbin** [comment]
@PowerUser64 which controller did you have? I have a non-nintendo branded controller that is not working. It is a PowerA controller, and while PowerA is licensed by nintendo, it is still different from the real Pro Controller.

This controller has worked for me playing other types of games through Steam and Wine, such as Rocket League. But it does not work with cemu, even after using this package, nintendo-hid-dkms, and joycond. I get the same issue mentioned at the beginning of this issue.

**Comment by AE0S01** [comment]
Hey guys, it says "Looking for Nintendo Switch controllers..." to me, but evtest reads my JoyCon, look`No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Power Button
/dev/input/event1:      Lid Switch
/dev/input/event10:     HD-Audio Generic Front Headphone
/dev/input/event11:     MOSART Semi. 2.4G Keyboard Mouse
/dev/input/event12:     MOSART Semi. 2.4G Keyboard Mouse
/dev/input/event13:     MOSART Semi. 2.4G Keyboard Mouse Consumer Control
/dev/input/event14:     MOSART Semi. 2.4G Keyboard Mouse System Control
/dev/input/event15:     MOSART Semi. 2.4G Keyboard Mouse
/dev/input/event16:     Nintendo Switch Right Joy-Con
/dev/input/event17:     Nintendo Switch Right Joy-Con IMU
/dev/input/event2:      Power Button
/dev/input/event3:      AT Translated Set 2 keyboard
/dev/input/event4:      Video Bus
/dev/input/event5:      Video Bus
/dev/input/event6:      SynPS/2 Synaptics TouchPad
/dev/input/event7:      HP WMI hotkeys
/dev/input/event8:      HD-Audio Generic HDMI/DP,pcm=3
/dev/input/event9:      HD-Audio Generic Mic`
