### ISSUE TITLE
Stopped working on the 8Bitdo Pro 2 gamepad in wired mode

### ISSUE THREAD

**Issue by anzix** [joaorb64/joycond-cemuhook#95]
Description of the problem:
By setting the S (Switch) mode in the gamepad, connecting the gamepad via USB wire, after entering the command `sudo joycond-cemuhook -v` writes that the hid_nintendo module is loaded and nothing happens after that, just an endless indication "Looking for Nintendo Switch controllers...". The connection simply does not happen

There is no such problem in Bluetooth mode, the command is executed successfully

About 2 months ago (maybe less) everything was fine, probably it was somehow affected by Linux kernel updates

System:
Arch Linux Zen kernel (6.8.2-zen2-1-zen)

Gamepad:
8Bitdo Pro 2 firmware version latest 3.04

Software:
The latest version of the joycond-cemuhook-git r126.afa7601-1 AUR package (latest commit)
The AUR package [game-devices-udev](https://aur.archlinux.org/packages/game-devices-udev) is also installed (Udev rules for the operation of 8Bitdo controllers in Cemu emulators and others)

**Comment by lbschenkel** [comment]
Look at https://github.com/joaorb64/joycond-cemuhook/pull/100

**Comment by anzix** [comment]
Thank you @lbschenkel , the problem is solved now.
